### PR TITLE
eNATL feedstock 

### PR DESCRIPTION
**Pull request by norlandrhagen**
A pruned version of this recipe is running locally for me. 

cc @SammyAgrawal 

If this seems good, we should give it a go on dataflow. 🚀 
image

### CODE REVIEW

**Review by SammyAgrawal — APPROVED** [review]
Allowing copy_to_local since dataset small; will continue trying to fix

**Comment by jbusecke** [comment]
@norlandrhagen @SammyAgrawal should we run this on dataflow?

**Comment by SammyAgrawal** [comment]
I think we can/ should. I would like to be walked through that process

**Comment by jbusecke** [comment]
Ill outline my steps here: 

1. I navigate to "Actions" and choose "Deploy Recipe... 
image

2. Notice that I cannot run the action from a fork branch 🤦‍♂️

**Comment by jbusecke** [comment]
@SammyAgrawal The steps I am taking now are outlined [here](https://github.com/leap-stc/LEAP_template_feedstock?tab=readme-ov-file#deploy-your-recipe-to-leaps-google-dataflow)!

**Pull request merged**
